import {cookies} from 'next/headers';
import {db} from '../db';
function initialPasswordHash(){return process.env.OWNER_INITIAL_PASSWORD_HASH}
function ownerUsername(){return process.env.OWNER_USERNAME||'kuladeep'}
const cookieName=process.env.NODE_ENV==='production'?'__Host-kuladeep_owner':'kuladeep_owner';
const enc=new TextEncoder();
export async function digest(value:string){const bytes=new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(value)));return Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('')}
export async function passwordHash(password:string,salt=crypto.randomUUID()){const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);const bytes=new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',salt:enc.encode(salt),iterations:100000,hash:'SHA-256'},key,256));return salt+':'+Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('')}
export async function initAuth(){await db.batch([db.prepare('CREATE TABLE IF NOT EXISTS owner_auth (id TEXT PRIMARY KEY,value TEXT NOT NULL)'),db.prepare('CREATE TABLE IF NOT EXISTS owner_sessions (id TEXT PRIMARY KEY,expires INTEGER NOT NULL)'),db.prepare('CREATE TABLE IF NOT EXISTS owner_login_limits (id TEXT PRIMARY KEY,count INTEGER NOT NULL,expires INTEGER NOT NULL)')]);}
export async function checkPassword(password:string){await initAuth();const row:any=await db.prepare("SELECT value FROM owner_auth WHERE id='password'").first();const hash=row?.value||initialPasswordHash();if(!hash)return false;return await passwordHash(password,hash.split(':')[0])===hash}
export async function createOwnerSession(){const token=crypto.randomUUID()+crypto.randomUUID();await db.prepare('INSERT INTO owner_sessions(id,expires) VALUES(?,?)').bind(await digest(token),Date.now()+8*3600000).run();return token}
export function sessionCookie(token:string){return {name:cookieName,value:token,httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'strict' as const,path:'/',maxAge:8*3600}}
export async function getPasswordOwner(){const token=(await cookies()).get(cookieName)?.value;if(!token)return null;await initAuth();const row:any=await db.prepare('SELECT expires FROM owner_sessions WHERE id=?').bind(await digest(token)).first();return row&&Number(row.expires)>Date.now()?{userId:'portfolio-owner',displayName:ownerUsername(),email:'owner@portfolio.local',fullName:null}:null}
export async function revokeSession(){const token=(await cookies()).get(cookieName)?.value;if(token){await initAuth();await db.prepare('DELETE FROM owner_sessions WHERE id=?').bind(await digest(token)).run()}}
export async function changeOwnerPassword(password:string){await db.batch([db.prepare("INSERT INTO owner_auth(id,value) VALUES('password',?) ON CONFLICT(id) DO UPDATE SET value=excluded.value").bind(await passwordHash(password)),db.prepare('DELETE FROM owner_sessions')])}
export function sameOrigin(req:Request){const origin=req.headers.get('origin');if(!origin)return false;const u=new URL(req.url);return origin===u.origin||origin==='https://'+req.headers.get('host')}
export async function loginLimited(req:Request){await initAuth();const ip=req.headers.get('cf-connecting-ip')||req.headers.get('x-nf-client-connection-ip')||'unknown';const id='owner-login:'+await digest(ip);const row:any=await db.prepare('SELECT count,expires FROM owner_login_limits WHERE id=?').bind(id).first();const now=Date.now();if(row&&Number(row.expires)>now&&Number(row.count)>=10)return true;await db.prepare('INSERT INTO owner_login_limits(id,count,expires) VALUES(?,1,?) ON CONFLICT(id) DO UPDATE SET count=CASE WHEN expires>? THEN count+1 ELSE 1 END,expires=CASE WHEN expires>? THEN expires ELSE excluded.expires END').bind(id,now+15*60000,now,now).run();return false}
export {ownerUsername};
