// Reviewed educational summaries. These are not personal diagnosis or treatment plans.
export const serviceKnowledge = [
  {id:'laparoscopy',title:'Laparoscopic / keyhole surgery',match:/\blaparoscop(?:y|ic)\b|\bkeyhole\b|\bminimally invasive\b/i,body:'Laparoscopic surgery uses small cuts, a camera and surgical instruments to operate inside the abdomen. It can be used for selected gallbladder, appendix, hernia and other operations. The appropriate approach depends on the condition and your health; sometimes open surgery is needed. Benefits and risks should be discussed with the surgeon.',urgent:'Recovery and aftercare vary by operation. Follow your own surgical team’s instructions.',source:'https://www.nhs.uk/tests-and-treatments/laparoscopy/'},
  {id:'gallstones',title:'Gallstones',match:/\bgall\s*stones?\b|\bgallbladder\b/i,body:'Gallstones are solid deposits that form in the gallbladder. They may cause upper abdominal pain, nausea or vomiting, although some cause no symptoms. Symptomatic gallstones may need gallbladder removal, often through keyhole surgery; symptom-free stones do not always need treatment.',urgent:'Persistent severe pain, fever or yellowing of the eyes or skin needs urgent assessment.',source:'https://www.niddk.nih.gov/health-information/digestive-diseases/gallstones'},
  {id:'appendix',title:'Appendicitis / appendix surgery',match:/\bappendi(?:x|citis|cectomy|ectomy)\b/i,body:'Appendicitis is inflammation and infection of the appendix. Pain may start near the belly button and move to the lower right abdomen, with nausea or fever. It needs urgent hospital assessment; surgery to remove the appendix is a common treatment.',urgent:'Worsening abdominal pain or pain moving to the lower right abdomen needs urgent assessment. Severe abdominal pain needs emergency care.',source:'https://www.nhs.uk/conditions/appendicitis/'},
  {id:'reflux',title:'Acid reflux and hiatus hernia',match:/\breflux\b|\bhiat(?:us|al)\b|\bheartburn\b|\bg[eo]rd\b/i,body:'Reflux means stomach contents flow back into the food pipe, causing heartburn or regurgitation. A hiatus hernia means part of the stomach moves through the diaphragm into the chest. Many people are managed without surgery; persistent symptoms may need tests and a discussion of anti-reflux or hernia surgery.',urgent:'Difficulty swallowing, unexplained weight loss or repeated vomiting needs prompt assessment. Vomiting blood or severe chest pain needs emergency care.',source:'https://www.nhs.uk/conditions/hiatus-hernia/'},
  {id:'hernia',title:'Hernia and abdominal wall repair',match:/\bhernia\b|\bawr\b|abdominal wall reconstruction/i,body:'A hernia happens when tissue pushes through a weak area in a muscle or abdominal wall, sometimes causing a bulge or discomfort. Types include groin, umbilical and incisional hernias. Assessment determines whether monitoring or repair is appropriate. Repair may be open or laparoscopic and may use mesh; complex abdominal wall defects need an individual surgical plan.',urgent:'A suddenly painful or firm bulge, vomiting or difficulty passing stool or gas needs urgent emergency assessment.',source:'https://www.niddk.nih.gov/health-information/digestive-diseases/inguinal-hernia'},
  {id:'piles',title:'Piles / haemorrhoids',match:/\bpiles?\b|\bh[ae]*morrhoids?\b/i,body:'Piles are enlarged blood vessels in or around the anus. They can cause itching, discomfort, lumps or bright-red bleeding. Treatment can include bowel-habit changes, clinic procedures or surgery depending on severity. Laser treatment is not automatically suitable for every patient.',urgent:'New or persistent rectal bleeding should be assessed rather than assumed to be piles. Heavy bleeding, faintness or severe pain needs urgent care.',source:'https://www.nhs.uk/conditions/piles-haemorrhoids/'},
  {id:'fissure',title:'Anal fissure',match:/\bfissures?\b/i,body:'An anal fissure is a small tear in the lining of the anus. It often causes sharp pain during or after passing stool and sometimes bright-red bleeding. Care may involve softening stools and clinician-directed treatment; persistent fissures sometimes need a procedure or surgery.',urgent:'Persistent bleeding or pain should be assessed to confirm the cause.',source:'https://www.nhs.uk/conditions/anal-fissure/'},
  {id:'fistula',title:'Anal fistula',match:/\bfistulas?\b/i,body:'An anal fistula is an abnormal tunnel between the anal canal and nearby skin, often following an abscess. It can cause discharge, repeated swelling or pain. It usually needs specialist assessment and a procedure; the approach depends on the tunnel and its relationship to the muscles controlling bowel movements.',urgent:'Painful swelling with fever or worsening illness needs urgent assessment for infection.',source:'https://www.nhs.uk/conditions/anal-fistula/'},
  {id:'pilonidal',title:'Pilonidal sinus',match:/\bpilonidal\b/i,body:'A pilonidal sinus is a small opening or tunnel in the skin near the top of the buttock cleft. Infection may cause pain, swelling or discharge. An abscess may need drainage; recurrent problems can need a procedure or surgery. A sinus without infection may not need an operation.',urgent:'A painful lump that bleeds or leaks pus needs prompt assessment.',source:'https://www.nhs.uk/conditions/pilonidal-sinus/'},
  {id:'veins',title:'Varicose veins',match:/\bvaricose\b|\bevla\b|\bevlt\b|\brfa\b|\bvenaseal\b|\bsclerotherapy\b/i,body:'Varicose veins are enlarged, twisted veins, usually in the legs, caused by veins not returning blood efficiently. They can cause aching, heaviness, swelling or skin changes. Assessment often includes duplex ultrasound. Options include laser or radiofrequency vein closure, foam treatment and other procedures; suitability depends on the scan and clinical assessment.',urgent:'Bleeding veins need urgent assessment. Sudden leg swelling or pain, especially with chest pain or breathlessness, needs urgent medical attention.',source:'https://www.nhs.uk/conditions/varicose-veins/'},
  {id:'foot',title:'Diabetic foot ulcers',match:/\bdiabetic\s+foot\b|\bfoot\s+(?:ulcers?|wounds?)\b/i,body:'A diabetic foot ulcer is an open wound on the foot in a person with diabetes. Reduced sensation and poor blood flow can delay healing, and a wound may be serious even without pain. Care needs prompt clinical assessment of the wound, circulation and infection, with dressings, pressure relief and diabetes management tailored by the care team.',urgent:'A new diabetic foot wound needs prompt assessment. Spreading redness, swelling, discharge, fever or dark tissue needs urgent care.',source:'https://www.myhealthlondon.nhs.uk/resources/internal/looking-after-your-diabetic-foot-ulcer/'},
  {id:'lumps',title:'Soft tissue swellings',match:/\blipomas?\b|\bcysts?\b|\bgangli?on\b|\bderm(?:oid|aid)\b|\bsoft tissue\b/i,body:'Soft tissue lumps have different causes. A lipoma is a fatty lump; a cyst is a sac containing fluid or other material, and a ganglion usually develops near a joint or tendon. An examination, and sometimes imaging or tissue testing, is needed to identify a lump. Observation or removal depends on the diagnosis and symptoms; not every lump should be assumed harmless.',urgent:'A growing, painful, hard or persistent lump should be assessed.',source:'https://www.nhs.uk/symptoms/lumps/'},
  {id:'glands',title:'Thyroid, parotid and salivary gland assessment',match:/\bthyroid\b|\bparotid\b|\bsalivary\b/i,body:'The thyroid is a gland in the neck, while salivary glands, including the parotid glands, produce saliva. A neck or gland lump can have several causes and needs examination. Tests may be needed before deciding whether observation or surgery is appropriate. The surgeon explains the diagnosis, benefits and risks before a treatment decision.',urgent:'A persistent or growing neck lump should be assessed. Difficulty breathing needs emergency care.',source:'https://www.nhs.uk/symptoms/lumps/'},
  {id:'colonoscopy',title:'Colonoscopy',match:/\bcolonoscopy\b/i,body:'Colonoscopy uses a flexible camera to examine the large bowel. It can help investigate bowel symptoms and allow tissue samples or removal of some polyps. Bowel preparation is required; follow the clinical team’s instructions, including advice about your usual medicines.',urgent:'Ask your clinical team about the benefits, risks and preparation for your situation.',source:'https://www.nhs.uk/tests-and-treatments/colonoscopy/'},
  {id:'ercp',title:'ERCP',match:/\bercp\b/i,body:'ERCP combines an endoscope with X-ray imaging to access the bile and pancreatic ducts. It can treat selected problems such as duct blockage. It has risks, including pancreatitis, so a specialist decides when it is appropriate and discusses alternatives.',urgent:'Preparation and aftercare must follow the specialist team’s instructions.',source:'https://www.guysandstthomas.nhs.uk/health-information/ercp-endoscopic-retrograde-cholangio-pancreatography'},
  {id:'endoscopy',title:'Endoscopy',match:/\bendoscop(?:y|ic)\b|upper gi/i,body:'Endoscopy uses a thin flexible camera to examine or treat problems inside the body. Upper GI endoscopy examines the food pipe, stomach and first part of the small intestine. It can help investigate symptoms or take tissue samples. The team explains preparation, comfort options and procedure risks.',urgent:'Do not change medicines or fasting instructions without checking with the clinical team.',source:'https://www.nhs.uk/tests-and-treatments/endoscopy/'}
];

export function specialtyReply(messages:{role:string,content:string}[]){
  const text=messages.at(-1)?.content||'';
  // Profile and booking questions are handled by the clinic facts or the AI provider.
  if(/\b(education|qualification|qualifications|fellowships?|experience|awards?|memberships?|appointment|booking|book|fee|cost|price|insurance)\b/i.test(text))return null;
  let topics=serviceKnowledge.filter(t=>t.match.test(text));
  const followup=/\b(symptoms?|causes?|treatment|surgery|operation|recovery|explain|tell me more|what about|diet|prevent|risks?|medicine|medication|tablet|dose|dosage|prescribe|antibiotic)\b/i.test(text);
  if(!topics.length&&followup){
    for(const m of [...messages.slice(0,-1)].reverse()){
      if(m.role!=='user')continue;
      topics=serviceKnowledge.filter(t=>t.match.test(m.content));
      if(topics.length)break;
    }
  }
  if(!topics.length)return null;
  if(/\b(medicine|medication|tablet|dose|dosage|prescribe|antibiotic)\b/i.test(text))return 'I can explain these conditions, but I cannot select medicines or doses. Please ask your treating clinician, who can consider your examination, medical history and other medicines.';
  if(/\b(my report|my scan|diagnose me|do i have|is this cancer)\b/i.test(text))return 'I cannot diagnose a condition or interpret a personal report in chat. Please arrange a clinical review with the doctor. I can explain what the condition or procedure means in general.';
  const recovery=/\b(recovery|recover|back to work|heal|healing|how long)\b/i.test(text)?'\n\nRecovery depends on the diagnosis, procedure and your health. Your surgeon will explain your expected recovery and when to return to work or exercise; this chat cannot promise a timeframe.':'';
  return topics.slice(0,3).map(t=>`${t.title}\n${t.body}\n\nWhen to seek care: ${t.urgent}\nLearn more: ${t.source}`).join('\n\n')+recovery+'\n\nThis is general information. Dr. Kuladeep needs to assess you before recommending treatment. You can request a consultation using WhatsApp below.';
}
